PVP_K180/Models/Renginys.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PVP_K180.Models
{
    public class Renginys
    {
        [DisplayName("Renginio ID")]
        public int id_Renginys { get; set; }
        [DisplayName("Pavadinimas")]
        public string pavadinimas { get; set; }
        [DisplayName("Aprašymas")]
        public string aprasymas { get; set; }
        [DisplayName("Reitingas")]
        public int reitingas { get; set; }
        [DisplayName("Renginio paskelbimo data")]
        [DisplayFormat(DataFormatString = "{0:yyyy-dd-MM HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime paskelbimo_data { get; set; }
        [DisplayName("Renginio pradžios data")]
        [DisplayFormat(DataFormatString = "{0:yyyy-dd-MM HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime pradzios_data { get; set; }
        [DisplayName("Renginio pabaigos data")]
        [DisplayFormat(DataFormatString = "{0:yyyy-dd-MM HH:mm}", ApplyFormatInEditMode = true)]
        public DateTime pabaigos_data { get; set; }

        [DisplayName("Adresas")]
        [Required]
        public string adresas { get; set; }

        [DisplayName("Kaina")]
        [Required]
        public double kaina { get; set; }

        public string busenos_pavadinimas { get; set; }

        [DisplayName("Ilgumos koordinates")]
        public double zemelapis_ilguma { get; set; }
        [DisplayName("Plokštumos koordinates")]
        public double zemelapis_platuma { get; set; }
        [DisplayName("Būsena")]
        public int renginio_busena { get; set; }
        [DisplayName("Sukurta vartotojo")]
        public int vartotojas_id { get; set; }

        public List<Nuotrauka> gautosNuotraukos { get; set; }
    }
}

PVP_K180/Controllers/RenginysController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PVP_K180.Repos;
using PVP_K180.Models;
using PVP_K180.ModelView;
using System.IO;
using PagedList;

namespace PVP_K180.Controllers
{
    public class RenginysController : Controller
    {

        private Renginys_Repos renginys_Repos = new Renginys_Repos();
        Nuotrauka_Repos nuotrauka_Repos = new Nuotrauka_Repos();
        private const int pageSize = 5;
        private const int pageSizeView = 6;

        // GET: Renginys
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult RenginioKurimas()
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (!Session["Role"].Equals("Administratorius"))
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        public ActionResult RenginioKurimas(Renginio_duomenys renginio_Duomenys)
        {
            int counter = 0;
            List<string> posiblesExtensions = new List<string>() { ".jpg", ".png", ".JPG", ".PNG", ".jpeg", ".JPEG" };
            Renginys_Repos renginys_Repos = new Renginys_Repos();
            renginio_Duomenys.renginys.vartotojas_id = (int)Session["UserID"];
            renginio_Duomenys.renginys.paskelbimo_data = DateTime.Now;

            if (Convert.ToDouble(TempData["RenginysLang"]) == 0 || Convert.ToDouble(TempData["RenginysLong"]) == 0)
            {
                TempData["Fail"] = "Turite patvirtinti teisingą lokaciją";
                return View();
            }

            renginio_Duomenys.renginys.zemelapis_ilguma = (float)Convert.ToDouble(TempData["RenginysLang"]);
            renginio_Duomenys.renginys.zemelapis_platuma = (float)Convert.ToDouble(TempData["RenginysLong"]);

            bool flag = renginys_Repos.Sukurti_Rengini(renginio_Duomenys.renginys);
            if (flag)
            {
                int lastIndex = renginys_Repos.Gauti_Paskutini_Prideto_Index();

                foreach (HttpPostedFileBase file in renginio_Duomenys.nuotraukos)
                {
                    if (file != null)
                    {
                        var InputFileName = Path.GetFileName(file.FileName);

                        var extension = Path.GetExtension(file.FileName);
                        if (!posiblesExtensions.Contains(extension))
                        {
                            TempData["Fail"] = "Įkeltas su netinkamu formatu";
                            return View();
                        }

                        var random = Guid.NewGuid() + InputFileName;
                        var ServerSavePath = Path.Combine(Server.MapPath("~/Nuotraukos/") + random);


                        file.SaveAs(ServerSavePath);
                        Nuotrauka nuotrauka = new Nuotrauka();
                        nuotrauka.nuotraukos_nuoroda = random;
                        nuotrauka.priskirtas_id = lastIndex;
                        nuotrauka_Repos.Prideti_Renginio_Nuotraukas(nuotrauka);

                    }
                }
                TempData["Succ"] = "Renginys sėkmingai sukurtas!";
            }
            else
            {
                TempData["Fail"] = "Renginys nesukurtas!";

            }
            return View();
        }

        public ActionResult GautiRenginius(int? busena, DateTime? nuo, DateTime? iki,int? page)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (!Session["Role"].Equals("Administratorius"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (Session["Message"] != null)
            {
                if (Convert.ToBoolean(Session["Message"]))
                {
                    Response.Write("<script type='text/javascript' language='javascript'> alert('Nuotrauka pridėta sėkmingai!')</script>");
                    Session.Remove("Message");
                }
                else
                {
                    Response.Write("<script type='text/javascript' language='javascript'> alert('Nuotrauka pridėta nesėkmingai!')</script>");
                    Session.Remove("Message");
                }
            }
            int pageNumber = (page ?? 1);
            List<Renginys> renginys = renginys_Repos.Gauti_Renginius();
            if (busena != null)
            {
                pageNumber = 1;
                renginys = renginys.Where(x => x.renginio_busena == busena).ToList();
            }
            if (nuo != null)
            {
                pageNumber = 1;
                var data = (DateTime)nuo;
                renginys = renginys.Where(x => x.pabaigos_data.Date >= (DateTime)data.Date).ToList();
            }

            if (iki != null)
            {
                pageNumber = 1;
                var data = (DateTime)iki;
                renginys = renginys.Where(x => x.pabaigos_data.Date <= (DateTime)data.Date).ToList();
            }
            return View(renginys.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult RedaguotiRengini(int id)
        {
            Renginys_Repos renginys_Repos = new Renginys_Repos();
            Renginys renginys = renginys_Repos.Gauti_Rengini(id);
            return View(renginys);
        }

        [HttpPost]
        public ActionResult RedaguotiRengini(int id, Renginys renginys)
        {
            renginys.id_Renginys = id;
            Renginys_Repos renginys_Repos = new Renginys_Repos();
            renginys.vartotojas_id = (int)Session["UserID"];
            renginys.paskelbimo_data = DateTime.Now;
            Renginys renginys2 = renginys_Repos.Gauti_Rengini(id);
            renginys.zemelapis_ilguma = renginys2.zemelapis_ilguma;
            renginys.zemelapis_platuma = renginys2.zemelapis_platuma;

            if (Convert.ToDouble(TempData["RenginysLang"]) == 0 || Convert.ToDouble(TempData["RenginysLong"]) == 0)
            {
                TempData["Fail"] = "Turite patvirtinti teisingą lokaciją";
                return View(renginys);
            }

            renginys.zemelapis_ilguma = Convert.ToDouble(TempData["RenginysLang"]);
            renginys.zemelapis_platuma = Convert.ToDouble(TempData["RenginysLong"]);

            bool flag = renginys_Repos.Redaguoti_Rengini(renginys);
            if (flag)
            {
                TempData["Succ"] = "Renginys sėkmingai redaguotas!";
            }
            else
            {
                TempData["Fail"] = "Renginys neredaguotas!";

                Response.Write("<script type='text/javascript' language='javascript'> alert('Projektas neredaguotas!')</script>");
            }
            return View(renginys);
        }


        public ActionResult Komentarai(int id)
        {
            KomentaroLangasRenginys komentaruLangas = new KomentaroLangasRenginys();
            komentaruLangas.parasytiKomentarai = renginys_Repos.Gauti_Renginio_Komentarus(id);
            Session["RenginioID"] = id;
            ViewBag.currentReng = id;
            komentaruLangas.parasytiKomentarai = komentaruLangas.parasytiKomentarai.OrderByDescending(x => x.parasymo_data).ToList();
            return View(komentaruLangas);
        }

        [HttpPost]
        public ActionResult Komentarai(int id, KomentaroLangasRenginys komentaras)
        {
            komentaras.rasomasKomentaras.fk_Vartotojasid_Vartotojas = Convert.ToInt32(Session["UserID"]);
            komentaras.rasomasKomentaras.parasymo_data = DateTime.Now;
            komentaras.rasomasKomentaras.priskirtas_id = id;
            renginys_Repos.Rasyti_Komentara(komentaras.rasomasKomentaras);
            TempData["SuccsessComment"] = "Komentaras sėkmingai parašytas";
            return RedirectToAction("Komentarai", new { id = id });
        }

        public ActionResult TrintiKomentara(int id)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            bool check = renginys_Repos.PatikrintiArGalimaTrinti(Convert.ToInt32(Session["UserID"]), id);
            if (check)
            {
                renginys_Repos.Trinti_Komentara(id);
                TempData["DeleteSucc"] = "Komentaras ištrintas sėkmingai";
            }
            else
            {
                TempData["DeleteFail"] = "Komentaro nepavyko ištrinti";
            }

            return RedirectToAction("Komentarai", new { id = Convert.ToInt32(Session["RenginioID"]) });
        }

        [HttpPost]
        public void IsaugotiLokacija(float x, float y)
        {
            TempData["RenginysLang"] = x;
            TempData["RenginysLong"] = y;
        }

        public ActionResult Renginiai(int? page)
        {
            List<Renginys> renginiai = renginys_Repos.Gauti_Renginius();

            for(var i = 0; i<renginiai.Count;i++)
            {
                var length = renginiai[i].aprasymas.Length;

                if(length > 200)
                {
                    renginiai[i].aprasymas = renginiai[i].aprasymas.Substring(0, 200);
                }
                renginiai[i].gautosNuotraukos = nuotrauka_Repos.Gauti__Renginiu_Nuotraukas(renginiai[i].id_Renginys);
            }

            int pageNumber = (page ?? 1);
            return View(renginiai.ToPagedList(pageNumber, pageSizeView));
        }

        public ActionResult DetaliInformacijaRenginys(int id)
        {
            Renginys renginys = renginys_Repos.Gauti_Rengini(id);
            renginys.gautosNuotraukos = nuotrauka_Repos.Gauti__Renginiu_Nuotraukas(id);
            return View(renginys);
        }

        public ActionResult KeistiRenginioBusena(int id)
        {

PVP_K180/Views/Renginys/Komentarai.cshtml
@model PVP_K180.ModelView.KomentaroLangasRenginys

@{
    ViewBag.Title = "Komentarai";
}


<style>
    .borderless td, .borderless th {
        border: none;
    }

    .boxShadow2 {
        box-shadow: 0 1px 5px rgb(0 0 0 / 0.2);
        margin: auto;
        border-radius: 4px;
        width: 100%;
        padding: 10px;
        margin-top: 10px;
        position: relative;
        background-color: white;
    }

    .textarea {
        -ms-box-sizing: border-box;
        box-sizing: border-box;
        display: block;
        border: 3px solid silver;
        width: 50%;
        font-size: 15px;
        line-height: 20px;
        min-height: 70px;
    }
</style>
<h2>Komentarai</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal boxShadow2">
    @if (TempData["SuccsessComment"] != null)
    {
        <p class="alert alert-success" id="successMessage">@Convert.ToString(TempData["SuccsessComment"])</p>
    }
    @if (TempData["DeleteSucc"] != null)
    {
        <p class="alert alert-success" id="successMessage">@Convert.ToString(TempData["DeleteSucc"])</p>
    }
    @if (TempData["DeleteFail"] != null)
    {
        <p class="alert alert-danger" id="successMessage">@Convert.ToString(TempData["DeleteFail"])</p>
    }
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    @if (Session["UserID"] != null)
    {
        <div style="">
            <div>
                <h4 style="color:lightgray">Komentaras</h4>
                <div class="col-sm-10">
                    @Html.EditorFor(model => model.rasomasKomentaras.komentaro_tekstas, new { htmlAttributes = new { @class = "textarea", @type="text" } })
                    @Html.ValidationMessageFor(model => model.rasomasKomentaras.komentaro_tekstas, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div style="margin-top:5px;margin-left:15px;" class="col-md-10">
                    <input type="submit" value="Rašyti" class="btn btn-default" />
                </div>
            </div>



            

        </div>
    }
    <link rel="stylesheet" href="~/Styles/comment.css" />
    <div class="comments-container">
        <ul id="comments-list" class="comments-list">
            <li>
                @foreach (var item in Model.parasytiKomentarai)
                {
                    <div class="comment-main-level">
                        <!-- Avatar -->
                        <div class="comment-avatar"><img src="~/Nuotraukos/@item.nuotrauka_location" alt=""></div>
                        <!-- Content -->
                        <div class="comment-box">
                            <div class="comment-head">
                                <h6 class="comment-name by-author"><a href="@(@Url.Action("ProfilioPerziura", "Vartotojas", new { id = item.fk_Vartotojasid_Vartotojas }))">@item.varotojo_slapyvardis</a></h6>
                                <span>@item.parasymo_data.ToString("yyyy-MM-dd")</span>
                                @if (Convert.ToInt32(Session["UserID"]) == item.fk_Vartotojasid_Vartotojas)
                                {
                                    <i class="fa fa-reply"><a href="@(@Url.Action("TrintiKomentara", "Renginys", new { id = item.id_Komentaras }))">Trint komentarą</a></i>
                                }
                                <i class="fa fa-heart"></i>
                            </div>
                            <div class="comment-content">
                                @item.komentaro_tekstas
                            </div>
                        </div>
                    </div>
                <li></li>
                }
            </ul>
        </div>
    </div>}
<div class="row" style="margin-top: 2vh; margin-left: 0px; float: left; margin-bottom:2vh;">
    @Html.ActionLink("< Atgal", "PerziuretiRengini", "Renginys", new { id = Convert.ToInt32(Session["RenginioID"]) }, new { @class = "btn btn-info ", @type = "button" })
</div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }

PVP_K180/Views/Renginys/PerziuretiRengini.cshtml
@model PVP_K180.Models.Renginys

@{
    ViewBag.Title = Model.pavadinimas;
}

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
      integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
      crossorigin="" />

<script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
        integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=="
        crossorigin=""></script>

<script src="~/Scripts/lightbox.js"></script>
<link href="~/Styles/lightbox.css" rel="stylesheet" />

<style>

    /* Create two equal columns that floats next to each other */
    .column {
        float: left;
        width: 50%;
        padding: 5px;
    }

    /* Clear floats after the columns */
    .row:after {
        content: "";
        display: table;
        clear: both;
    }

    .boxShadow2 {
        box-shadow: 0 1px 5px rgb(0 0 0 / 0.2);
        margin: auto;
        border-radius: 4px;
        width: 100%;
        padding: 10px;
        margin-top: 10px;
        position: relative;
        background-color: white;
    }

    .customImg {
        max-height: 200px;
        max-width: 300px;
        padding-top: 1vh;
    }

    #map {
        height: 500px;
    }

    .customImg {
        max-height: 100px;
        max-width: 200px;
        padding-top: 1vh;
    }

    .marker-position {
        position: absolute;
        bottom: 0;
        left: 0;
        z-index: 999;
        padding: 10px;
        font-weight: 700;
        background-color: #fff;
    }
</style>


<script src="https://kit.fontawesome.com/2e7ea6ec96.js" crossorigin="anonymous"></script>
<h2>@Model.pavadinimas</h2>
<link href="~/Styles/SidePanel.css" rel="stylesheet" />
<div class="row">
    <div class="column">
        <div class="boxShadow2">
            <div>
                @if (Model.gautosNuotraukos.Count != 0)
                {
                    <img style="width:100%" src="~/Nuotraukos/@Model.gautosNuotraukos[0].nuotraukos_nuoroda" />
                }
                else
                {
                    <img style="width:100%" src="https://codeacoustics.files.wordpress.com/2017/06/pyramid-stage.png?w=1024&h=614&crop=1" />
                }

            </div>
            <div style="margin-top:1vh">
                <p>@Html.Raw(Model.aprasymas)</p>
            </div>

        </div>

    </div>
    <div class="column">
        <div class="boxShadow2">
            <div class="sticky-items static-top">
                <div class="main-info">
                    <div class="time-box">
                        <div class="date-time-wrap">
                            <span class="time-date">@Model.pradzios_data.ToString("yyyy-MM-dd")</span> <span class="time-h">@Model.pradzios_data.ToString("HH:mm")</span>
                        </div>
                        <div class="duration-wrap">
                            <div class="duration-text">@Model.pabaigos_data.ToString("yyyy-MM-dd")</div>
                            <div class="duration">
                                @Model.pabaigos_data.ToString("HH:mm")
                            </div>
                        </div>
                    </div>
                    <div class="details-wrap">
                        <div class="type with-icon">
                            <div class="title"> <i class="icon fa-solid fa-clock"></i><span style="margin-left:-20px">Renginio būsena</span></div>
                            <p title="@Model.busenos_pavadinimas">
                                <span>@Model.busenos_pavadinimas</span>
                            </p>
                        </div>
                        <div class="place with-icon">

                            <div class="title"><i class="icon fa-solid fa-location-dot"></i><span style="margin-left:-20px">Vieta</span></div>
                            <p>
                                <a class="open-list open-list" data-toggle="modal" data-target=".boostrapmodal" rel="follow" title="Chemijos g. 4B" href="">
                                    @Model.adresas <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                                </a>
                            </p>

                        </div>
                    </div>
                </div>

                @if (Model.kaina == 0)
                {


                    <div class="ticket  ">
                        <span style="color:green" class="in-event">NEMOKAMA</span>
                    </div>
                }
                else
                {
                    <div class="ticket  ">
                        <span class="in-event">Kaina: <span style="color:green">@Model.kaina €</span> </span>
                    </div>
                }

            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class=" column">
        <div style="" class="boxShadow2">
            <h4>Nuotraukų galerija</h4>
            <hr />
            @if (Model.gautosNuotraukos.Count != 0)
            {
                <div class="containerPhoto">
                    <div class="gallery">
                        @foreach (var item in Model.gautosNuotraukos)
                        {
                            <a href="~/Nuotraukos/@item.nuotraukos_nuoroda" data-lightbox="models" data-title="@item.nuotraukos_nuoroda">
                                <img class="customImg" src="~/Nuotraukos/@item.nuotraukos_nuoroda" />
                            </a>
                        }
                    </div>
                </div>
            }
            else
            {
                <p>Nuotraukų nebuvo pridėta</p>
            }
        </div>
    </div>
    <div class=" column">
    </div>
</div>

<div class="row">
    <div class=" column">
        <div style="" class="boxShadow2">
            @Html.ActionLink("Komentarai", "Komentarai", "Renginys", new { id = Model.id_Renginys }, new { @class = "btn btn-success ", @type = "button" })
        </div>
    </div>
    <div class=" column">
    </div>
</div>



<div class="row" style="margin-top: 2vh; margin-left: -3px; margin-bottom: 10px; float:left">

    <input type="submit" value="< Atgal" onclick="@("window.location.href='" + @Url.Action("Renginiai", "Renginys") + "'");" class="btn btn-info" />
</div>

<div id="myModal" class="modal fade boostrapmodal">
    <div class="modal-dialog modal-lg modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <b>Renginio vieta</b>
            </div>

            <div class="modal-body">
                <div class="mapStyle">

                    <div id="map"></div>
                </div>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-dismiss="modal">Uždaryti</button>
            </div>
        </div>
    </div>
</div>

<script src="~/Scripts/jquery-3.4.1.min.js"></script>
<script>
    var arGaliPrideti = true;
    /* eslint-disable no-undef */
    /**
     * add move and delete marker
     */

    // config map
    let config = {
        minZoom: 1,
        maxZoom: 18,
    };
    // magnification with which the map will start
    const zoom = 15;
    // co-ordinates
    const lat = '@Model.zemelapis_ilguma'.replace(",", ".");
    const lng = '@Model.zemelapis_platuma'.replace(",", ".");


    // calling map
        const map = L.map("map", config).setView([lat, lng], zoom);
        var main = L.marker([lat, lng]).addTo(map).bindPopup('@Model.pavadinimas');

    // Used to load and display tile layers on the map
    // Most tile servers require attribution, which you can set under `Layer`
    L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
        attribution:
            '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    }).addTo(map);

        $(document).ready(function () {

            $('#myModal').on('shown.bs.modal', function () {
                console.log("Find");
                map.invalidateSize();
            });
        })

</script>

PVP_K180/Views/Renginys/PridetiNuotraukuRenginiui.cshtml
@model PVP_K180.ModelView.Nuotrauku_Duomenys

@{
    ViewBag.Title = "Nuotraukų pridėjimas";
}

<style>
    .boxShadow {
        box-shadow: 0 1px 10px rgb(0 0 0 / 0.2);
        border-radius: 5px;
        width: 100%;
        padding: 10px;
        position: relative;
        background-color: white;
    }
</style>



@using (Html.BeginForm("PridetiNuotraukuRenginiui", "Renginys", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div style="margin-top:20px" class="form-horizontal boxShadow">
    <h2>Pridėti nuotraukas</h2>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.nuotraukos, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.nuotraukos, "", new { @type = "file", @multiple = "multiple" })
            @Html.ValidationMessageFor(model => model.nuotraukos, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Išsaugoti" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div style="margin-top: 30px;">
    <input type="submit" value="< Atgal" onclick="@("window.location.href='" + @Url.Action("GautiRenginius", "Renginys") + "'");" class="btn btn-info" />
</div>

PVP_K180/Views/Renginys/Renginiai.cshtml
@model PagedList.IPagedList<PVP_K180.Models.Renginys>
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = "Renginiai";
}

<link href="~/Styles/EventStyle.css" rel="stylesheet" />

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css">
    <link rel="stylesheet" href="./style.css">
    <title>Events Ticket Card</title>
</head>
<body>
    <div class="container">

        @foreach (var item in Model)
        {
            <div class="item-container">
                <div class="img-container">
                    @if (item.gautosNuotraukos.Count != 0)
                    {
                        <img src="~/Nuotraukos/@item.gautosNuotraukos[0].nuotraukos_nuoroda" alt="Event image">
                    }
                    else
                    {
                        <img src="https://www.lrt.lt/img/2019/11/17/550825-741847-756x425.jpg" alt="Event image">
                    }
                </div>

                <div class="body-container">
                    <div class="overlay"></div>

                    <div class="event-info">
                        <p class="title">@item.pavadinimas</p>
                        <div class="separator"></div>
                        @if (item.kaina == 0)
                        {
                            <p class="price">Nemokama</p>
                        }
                        else
                        {
                            <p class="price">@item.kaina €</p>
                        }
                        <div class="additional-info">
                            <p class="info">
                                <i class="fas fa-map-marker-alt"></i>
                                @item.adresas
                            </p>
                            <p class="info">
                                <i class="far fa-calendar-alt"></i>
                                @item.pradzios_data.ToString("yyyy-MM-dd HH:mm")
                            </p>

                            <p class="info description">
                                @item.aprasymas <span>daugiau...</span>
                            </p>
                        </div>
                    </div>
                    <span style="text-align:center;">
                        @Html.ActionLink("INFORMACIJA", "PerziuretiRengini", "Renginys", new { id = item.id_Renginys }, new { @class = "action", @type = "button" })
                    </span>


                </div>
            </div>
        }
    </div>

</body>

<div id="pager" style="text-align:center;flex:auto">
    @Html.PagedListPager(Model, page => Url.Action("Naujienos", new { page }))
</div>
@*
        <div class="row" style="">
        <p>
            <input type="submit" value="< Atgal" onclick="@("window.location.href='" + @Url.Action("Index", "Home") + "'");" class="btn btn-info" />
        </p>
    </div>
*@


</html>