PVP_K180/Models/Projektas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PVP_K180.Models
{
    public class Projektas
    {
        [DisplayName("Projekto id")]
        public int id_Projektas { get; set; }

        [DisplayName("Pavadinimas")]
        [Required(ErrorMessage = "Privalo būti įvestas klausimas")]
        public string pavadinimas { get; set; }

        [DisplayName("Aprašymas")]
        [Required(ErrorMessage = "Privalo būti įvestas klausimas")]
        [AllowHtml]
        public string aprasymas { get; set; }

        [DisplayName("Būsena")]
        public int projekto_busena { get; set; }

        [DisplayName("Kūrėjo ID")]
        public int fk_Vartotojasid_Vartotojas { get; set; }

        [DisplayName("Sukūrimo data")]
        public DateTime sukurimo_data { get; set; }

        public List<Nuotrauka> gautosNuotraukos { get; set; }
    }
}

PVP_K180/Controllers/ProjektasController.cs
using PagedList;
using PVP_K180.Models;
using PVP_K180.ModelView;
using PVP_K180.Repos;
using System;
using System.Collections.Generic;
using System.IO;
using System.Web;
using System.Web.Mvc;

namespace PVP_K180.Controllers
{
    public class ProjektasController : Controller
    {
        private Projektas_Repos projektas_Repos = new Projektas_Repos();
        private Nuotrauka_Repos nuotrauka_Repos = new Nuotrauka_Repos();
        string[] menesiai = new string[12] { "SAU", "VAS", "KOV", "BAL", "GEG", "BIR", "LIE", "LAP", "RUG", "SPA", "LAP", "GRU" };
        private const int pageSize = 5;
        private const int pageSizeView = 6;

        // GET: Projektas
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ProjektoKurimas()
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (!Session["Role"].Equals("Administratorius"))
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        public ActionResult ProjektoKurimas(Projekto_duomenys projekto_Duomenys)
        {
            List<string> posiblesExtensions = new List<string>() { ".jpg", ".png", ".JPG", ".PNG", ".jpeg", ".JPEG" };
            Projektas_Repos projektas_Repos = new Projektas_Repos();
            projekto_Duomenys.projektas.sukurimo_data = DateTime.Now;
            projekto_Duomenys.projektas.fk_Vartotojasid_Vartotojas = (int)Session["UserID"];
            bool flag = projektas_Repos.Sukurti_Projekta(projekto_Duomenys.projektas);
            if (flag)
            {
                int lastIndex = projektas_Repos.Gauti_Paskutini_Prideto_Index();

                foreach (HttpPostedFileBase file in projekto_Duomenys.nuotraukos)
                {
                    if (file != null)
                    {
                        var InputFileName = Path.GetFileName(file.FileName);

                        var extension = Path.GetExtension(file.FileName);
                        if (!posiblesExtensions.Contains(extension))
                        {
                            TempData["Fail"] = "Įkeltas su netinkamu formatu";
                            return View();
                        }

                        var random = Guid.NewGuid() + InputFileName;
                        var ServerSavePath = Path.Combine(Server.MapPath("~/Nuotraukos/") + random);


                        file.SaveAs(ServerSavePath);
                        Nuotrauka nuotrauka = new Nuotrauka();
                        nuotrauka.nuotraukos_nuoroda = random;
                        nuotrauka.priskirtas_id = lastIndex;
                        nuotrauka_Repos.Prideti_Projekto_Nuotraukas(nuotrauka);

                    }
                }
                TempData["Succ"] = "Projektas sėkmingai sukurtas!";
                Response.Write("<script type='text/javascript' language='javascript'> alert('Projektas sėkmingai sukurtas!')</script>");
            }
            else
            {
                TempData["Fail"] = "Projektas nesukurtas!";

            }

            return View();
        }

        public ActionResult RedaguotiProjekta(int id)
        {
            Projektas_Repos projektas_Repos = new Projektas_Repos();
            Projektas projektas = projektas_Repos.Gauti_Projekta(id);
            return View(projektas);
        }

        [HttpPost]
        public ActionResult RedaguotiProjekta(int id, Projektas projektas)
        {
            projektas.id_Projektas = id;
            Projektas_Repos projektas_Repos = new Projektas_Repos();
            projektas.fk_Vartotojasid_Vartotojas = (int)Session["UserID"];
            bool flag = projektas_Repos.Redaguoti_Projekta(projektas);
            if (flag)
            {
                TempData["Succ"] = "Projektas sėkmingai redaguotas!";
            }
            else
            {
                TempData["Fail"] = "Projektas neredaguotas!";
            }
            return View(projektas);
        }

        public ActionResult TrintiProjekta(int id)
        {
            Projektas_Repos projektas_Repos = new Projektas_Repos();
            bool flag = projektas_Repos.Trinti_Projekta(id);
            return RedirectToAction("GautiProjektus");
        }

        public ActionResult GautiProjektus(int? page)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (!Session["Role"].Equals("Administratorius"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (Session["Message"] != null)
            {
                if (Convert.ToBoolean(Session["Message"]))
                {
                    Response.Write("<script type='text/javascript' language='javascript'> alert('Nuotrauka pridėta sėkmingai!')</script>");
                    Session.Remove("Message");
                }
                else
                {
                    Response.Write("<script type='text/javascript' language='javascript'> alert('Nuotrauka pridėta nesėkmingai!')</script>");
                    Session.Remove("Message");
                }
            }

            Projektas_Repos projektas_Repos = new Projektas_Repos();
            List<Projektas> projektas = projektas_Repos.Gauti_Projektus();
            int pageNumber = (page ?? 1);
            return View(projektas.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult Komentarai(int id)
        {
            KomentaroLangasProjektas komentaruLangas = new KomentaroLangasProjektas();
            komentaruLangas.parasytiKomentarai = projektas_Repos.Gauti_Projekto_Komentarus(id);
            TempData["ProjektoID"] = id;
            return View(komentaruLangas);
        }

        [HttpPost]
        public ActionResult Komentarai(int id, KomentaroLangasProjektas komentaras)
        {
            komentaras.rasomasKomentaras.fk_Vartotojasid_Vartotojas = Convert.ToInt32(Session["UserID"]);
            komentaras.rasomasKomentaras.parasymo_data = DateTime.Now;
            komentaras.rasomasKomentaras.priskirtas_id = id;
            projektas_Repos.Rasyti_Komentara(komentaras.rasomasKomentaras);
            TempData["SuccsessComment"] = "Komentaras sėkmingai parašytas";
            return RedirectToAction("Komentarai", new { id = id });
        }

        public ActionResult TrintiKomentara(int id)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            bool check = projektas_Repos.PatikrintiArGalimaTrinti(Convert.ToInt32(Session["UserID"]), id);
            if (check)
            {
                projektas_Repos.Trinti_Komentara(id);
                TempData["DeleteSucc"] = "Komentaras ištrintas sėkmingai";
            }
            else
            {
                TempData["DeleteFail"] = "Komentaro nepavyko ištrinti";
            }

            return RedirectToAction("Komentarai", new { id = Convert.ToInt32(TempData["ProjektoID"]) });
        }

        public ActionResult Projektai(int? page)
        {
            Projektas_Repos projektas_Repos = new Projektas_Repos();
            List<ProjektuPerziura> projektas = projektas_Repos.Gauti_Projektus_Atvaizdavimui();

            for(var i = 0; i < projektas.Count; i++)
            {
                projektas[i].diena = projektas[i].sukurimo_data.Day;
                projektas[i].menuo = menesiai[projektas[i].sukurimo_data.Month-1];
                List<Nuotrauka> nuotraukos = nuotrauka_Repos.Gauti_Projektu_Nuotraukas(projektas[i].id_Projektas);
                projektas[i].pradine_nuotrauka = nuotraukos[0].nuotraukos_nuoroda;
                if (projektas[i].aprasymas.Length > 150)
                {
                    projektas[i].aprasymas = projektas[i].aprasymas.Substring(0, 150);
                }
               
            }
            int pageNumber = (page ?? 1);
            return View(projektas.ToPagedList(pageNumber, pageSizeView));
        }

        public ActionResult DetaliInformacijaProjektas(int id)
        {
            Projektas projektas = projektas_Repos.Gauti_Projekta(id);
            projektas.gautosNuotraukos = nuotrauka_Repos.Gauti_Projektu_Nuotraukas(id);
            return View(projektas);
        }

        public ActionResult PridetiNuotraukuProjektui(int id)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (!Session["Role"].Equals("Administratorius"))
            {
                return RedirectToAction("Index", "Home");
            }

            Nuotrauku_Duomenys nuotrauku_Duomenys = new Nuotrauku_Duomenys();
            Session["ProjektoID"] = id;
            return View(nuotrauku_Duomenys);
        }

        [HttpPost]
        public ActionResult PridetiNuotraukuProjektui(Nuotrauku_Duomenys nuotrauku_Duomenys)
        {
            List<string> posiblesExtensions = new List<string>() { ".jpg", ".png", ".JPG", ".PNG", ".jpeg", ".JPEG" };
            nuotrauku_Duomenys.priskirtas_id = Convert.ToInt32(Session["ProjektoID"]);
            Session.Remove("ProjektoID");

            int photoCount = 0;
            foreach (HttpPostedFileBase file in nuotrauku_Duomenys.nuotraukos)
            {
                if (file != null)
                {
                    photoCount++;
                    var InputFileName = Path.GetFileName(file.FileName);
                    var extension = Path.GetExtension(file.FileName);

                    if (!posiblesExtensions.Contains(extension))
                    {
                        Response.Write("<script type='text/javascript' language='javascript'> alert('Įkeltas su netinkamu formatu')</script>");

PVP_K180/Views/Projektas/DetaliInformacijaProjektas.cshtml
@model PVP_K180.Models.Projektas

@{
    ViewBag.Title = "DetaliInformacijaProjektas";
}
<link href="~/Styles/photoStyle.css" rel="stylesheet" />
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
      integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
      crossorigin="" />
<link href="~/Styles/lightbox.css" rel="stylesheet" />

<style>
    .boxShadow {
        box-shadow: 0 1px 10px rgb(0 0 0 / 0.2);
        margin: auto;
        border-radius: 5px;
        width: 75%;
        text-align: center;
        padding: 10px;
        margin-top: 30px;
        position: relative;
        word-wrap: break-word;
    }
</style>

<h2 style="text-align:center">Detali Informacija</h2>

<div>

    <div class="boxShadow">
        <p style="text-align:left;font-size:20px; font-weight:bold">
            Projektas #@Model.id_Projektas
        </p>
        <hr />
    </div>

    <div class="boxShadow" style="text-align:left;font-size:15px;">
        <p style="text-align: left; font-size: 20px; font-weight: bold">@Html.DisplayNameFor(model => model.pavadinimas)</p>
        <hr />
        <p>@Html.DisplayFor(model => model.pavadinimas)</p>
    </div>

    <div class="boxShadow" style="text-align:left;font-size:15px;">
        <p style="text-align: left; font-size: 20px; font-weight: bold">@Html.DisplayNameFor(model => model.aprasymas)</p>
        <hr />
        <p>@Html.DisplayFor(model => model.aprasymas)</p>
    </div>

    <div class="boxShadow" style="text-align:left;font-size:15px;">
        <p style="text-align: left; font-size: 20px; font-weight: bold">@Html.DisplayNameFor(model => model.projekto_busena)</p>
        <hr />
        <p>@Html.DisplayFor(model => model.projekto_busena)</p>
    </div>

    <div class="boxShadow" style="text-align:left;font-size:15px;">
        <p style="text-align: left; font-size: 20px; font-weight: bold"> @Html.DisplayNameFor(model => model.fk_Vartotojasid_Vartotojas)</p>
        <hr />
        <p> @Html.DisplayFor(model => model.fk_Vartotojasid_Vartotojas)</p>
    </div>

    <script src="~/Scripts/lightbox.js"></script>
    <div class="boxShadow">

        <p style="text-align: left; font-size: 20px; font-weight: bold">Nuotraukos</p>
        <hr />
        @if (Model.gautosNuotraukos.Count != 0)
        {
            <div class="containerPhoto">
                <div class="gallery">
                    @foreach (var item in Model.gautosNuotraukos)
                    {
                        <a href="~/Nuotraukos/@item.nuotraukos_nuoroda" data-lightbox="models" data-title="@item.nuotraukos_nuoroda">
                            <img src="~/Nuotraukos/@item.nuotraukos_nuoroda" />
                        </a>
                    }
                </div>
            </div>
        }
        else
        {
            <p>Nuotraukų nebuvo pridėta</p>
        }

    </div>
</div>
<div style="margin-top: 30px;">
    <input type="submit" value="< Atgal" onclick="@("window.location.href='" + @Url.Action("GautiProjektus") + "'");" class="btn btn-info" />
</div>

PVP_K180/Views/Projektas/GautiNuotraukasProjekto.cshtml
@model IEnumerable<PVP_K180.Models.Nuotrauka>

@{
    ViewBag.Title = "GautiNuotraukasProjekto";
}

<h2>Nuotraukų sąrašas</h2>


<style>
    .boxShadow {
        box-shadow: 0 1px 10px rgb(0 0 0 / 0.2);
        border-radius: 5px;
        width: 100%;
        padding: 10px;
        position: relative;
        background-color: white;
    }

    .img{
        max-width:200px;
        max-height:200px;
    }
</style>


<div style="margin-top:20px" class="boxShadow">


    <table class="table">
        <tr>
            <th>
                Nuotrauka
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img class="img" src="@(item.nuotraukos_nuoroda)" />
                </td>
                <td>
                    @Html.ActionLink("Ištrinti", "TrintiNuotrauka", new { id = item.id_Nuotrauka }, new { @class="btn btn-danger"})
                </td>
            </tr>

        }


    </table>
</div>
<div style="margin-top: 30px;">
    <input type="submit" value="< Atgal" onclick="@("window.location.href='" + @Url.Action("GautiProjektus") + "'");" class="btn btn-info" />
</div>

PVP_K180/Views/Projektas/Komentarai.cshtml
@model PVP_K180.ModelView.KomentaroLangasProjektas

@{
    ViewBag.Title = "Komentarai";
}


<style>
    .borderless td, .borderless th {
        border: none;
    }

    .boxShadow2 {
        box-shadow: 0 1px 5px rgb(0 0 0 / 0.2);
        margin: auto;
        border-radius: 4px;
        width: 100%;
        padding: 10px;
        margin-top: 10px;
        position: relative;
        background-color: white;
    }

    .textarea {
        -ms-box-sizing: border-box;
        box-sizing: border-box;
        display: block;
        border: 3px solid silver;
        width: 50%;
        font-size: 15px;
        line-height: 20px;
        min-height: 70px;
    }
</style>
<h2>Komentarai</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal boxShadow2">
        @if (TempData["SuccsessComment"] != null)
        {
            <p class="alert alert-success" id="successMessage">@Convert.ToString(TempData["SuccsessComment"])</p>
        }
        @if (TempData["DeleteSucc"] != null)
        {
            <p class="alert alert-success" id="successMessage">@Convert.ToString(TempData["DeleteSucc"])</p>
        }
        @if (TempData["DeleteFail"] != null)
        {
            <p class="alert alert-danger" id="successMessage">@Convert.ToString(TempData["DeleteFail"])</p>
        }
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @if (Session["UserID"] != null)
        {
            <div style="">
                <div>
                    <h4 style="color:lightgray">Komentaras</h4>
                    <div class="col-sm-10">
                        @Html.EditorFor(model => model.rasomasKomentaras.komentaro_tekstas, new { htmlAttributes = new { @class = "textarea", @type = "text" } })
                        @Html.ValidationMessageFor(model => model.rasomasKomentaras.komentaro_tekstas, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div style="margin-top:5px;margin-left:15px;" class="col-md-10">
                        <input type="submit" value="Rašyti" class="btn btn-default" />
                    </div>
                </div>


            </div>
        }
        <link rel="stylesheet" href="~/Styles/comment.css" />
        <div class="comments-container">
            <ul id="comments-list" class="comments-list">
                <li>
                    @foreach (var item in Model.parasytiKomentarai)
                    {

                        <div class="comment-main-level">
                            <!-- Avatar -->
                            <div class="comment-avatar"><img src="~/Nuotraukos/@item.nuotrauka_location" alt=""></div>
                            <!-- Content -->
                            <div class="comment-box">
                                <div class="comment-head">
                                    <h6 class="comment-name by-author"><a href="@(@Url.Action("ProfilioPerziura", "Vartotojas", new { id = item.fk_Vartotojasid_Vartotojas }))">@item.varotojo_slapyvardis</a></h6>
                                    <span>@item.parasymo_data.ToString("yyyy-MM-dd")</span>
                                    @if (Convert.ToInt32(Session["UserID"]) == item.fk_Vartotojasid_Vartotojas)
                                    {
                                        <i class="fa fa-reply"><a href="@(@Url.Action("TrintiKomentara", "Renginys", new { id = item.id_Komentaras }))">Trint komentarą</a></i>
                                    }
                                    <i class="fa fa-heart"></i>
                                </div>
                                <div class="comment-content">
                                    @item.komentaro_tekstas
                                </div>
                            </div>
                        </div>
                    <li></li>
                }
                </ul>
            </div>
        </div>}
<div class="row" style="margin-top: 2vh; margin-left: 0px; float: left; margin-bottom:2vh;">
    @Html.ActionLink("< Atgal", "ProjektoInformacija", "Projektas", new { id = Convert.ToInt32(Session["ProjektoID"]) }, new { @class = "btn btn-info ", @type = "button" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PVP_K180/Views/Projektas/PridetiNuotraukuProjektui.cshtml
@model PVP_K180.ModelView.Nuotrauku_Duomenys

@{
    ViewBag.Title = "Nuotraukų pridėjimas";
}


<style>
    .boxShadow {
        box-shadow: 0 1px 10px rgb(0 0 0 / 0.2);
        border-radius: 5px;
        width: 100%;
        padding: 10px;
        position: relative;
        background-color: white;
    }
</style>



@using (Html.BeginForm("PridetiNuotraukuProjektui", "Projektas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div style="margin-top:20px" class="form-horizontal boxShadow">
    <h2>Pridėti nuotraukas</h2>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.nuotraukos, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.nuotraukos, "", new { @type = "file", @multiple = "multiple" })
            @Html.ValidationMessageFor(model => model.nuotraukos, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Išsaugoti" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div style="margin-top: 30px;">
    <input type="submit" value="< Atgal" onclick="@("window.location.href='" + @Url.Action("GautiProjektus", "Projektas") + "'");" class="btn btn-info" />
</div>

PVP_K180/Views/Projektas/Projektai.cshtml
@model PagedList.IPagedList<PVP_K180.ModelView.ProjektuPerziura>
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = "Projektai";
}
<link href="~/Styles/ProjectStyle.css" rel="stylesheet" />
<script src="https://kit.fontawesome.com/2e7ea6ec96.js" crossorigin="anonymous"></script>
<h2 style="text-align:center">Projektai</h2>
<div style="align-content:center; margin-top:20px;" class="row">
    @foreach (var item in Model)
    {
        <div class="column">
            <figure class="snip1493" style="height:500px">
                <div class="image">
                    <img src="~/Nuotraukos/@item.pradine_nuotrauka" alt="ls-sample1" />
                </div>
                <figcaption>
                    <div class="date"><span class="day">@item.diena</span><span class="month">@item.menuo</span></div>
                    <h3>@item.pavadinimas</h3>
                    <p>
                        @Html.Raw(item.aprasymas)
                    </p>
                    <footer>
                        <div class="love"><i class="ion-heart"></i>@item.ivertinimas</div>
                        <div class="comments"><i class="ion-chatboxes"></i>@item.komenetarai</div>
                        <div class="comments"><i class="fa-solid fa-check"></i>@item.busena</div>
                    </footer>
                </figcaption>
                <a>@Html.ActionLink(" ", "ProjektoInformacija", "Projektas", new { id = item.id_Projektas }, new { @class = "action", @type = "button" })</a>
            </figure>
        </div>
    }
</div>

<div id="pager" style="text-align:center">
    @Html.PagedListPager(Model, page => Url.Action("Naujienos", new { page }))
</div>

<div class="row" style="margin-top:2vh;margin-left:20px;margin-bottom:10px; float:left">
    <input type="submit" value="< Atgal" onclick="@("window.location.href='" + @Url.Action("Index", "Home") + "'");" class="btn btn-info" />
</div>
<script>

</script>

PVP_K180/Views/Projektas/ProjektoInformacija.cshtml
@model PVP_K180.ModelView.ProjektoPerziurosPuslapis
@{
    ViewBag.Title = "ProjektoInformacija";
}

<script src="~/Scripts/lightbox.js"></script>
<link href="~/Styles/lightbox.css" rel="stylesheet" />

<style>
    .boxShadow2 {
        box-shadow: 0 1px 5px rgb(0 0 0 / 0.2);
        margin: auto;
        border-radius: 4px;
        width: 100%;
        padding: 10px;
        margin-top: 30px;
        position: relative;
        background-color: white;
    }

    .customImg {
        max-height: 200px;
        max-width: 200px;
        padding-top: 1vh;
    }
</style>

<div class="boxShadow2">
    <p style="text-align:right">
        Publikuota: @Model.perziura.sukurimo_data.ToString("yyyy-MM-dd")
        <span style="float:left">
            Būsena: <span style="font-weight:bold">@Model.perziura.busena</span>
        </span>
    </p>
    <hr />
    <p style="font-size:30px">@Model.projektas.pavadinimas</p>
    <hr />
    <p>@Html.Raw(Model.projektas.aprasymas)</p>
</div>

<div style="display:flex; align-content:space-between;flex-wrap:wrap;flex-direction:column-reverse">
    <div style="margin-top:10px;width:25%;display:flex"; class="">
        <div>
            <a>@Html.ActionLink("Dalyvauti diskusijoje >", "Komentarai", "Projektas", new { id = Model.projektas.id_Projektas }, new { @class = "action btn btn-success", @type = "button" })</a>
        </div>

    </div>
</div>

<div style="align-items:center" class="boxShadow2">
    <H4>Nuotraukų galerija</H4>
    <hr />
    @if (Model.projektas.gautosNuotraukos.Count != 0)
    {
        <div class="containerPhoto">
            <div class="gallery">
                @foreach (var item in Model.projektas.gautosNuotraukos)
                {
                    <a href="~/Nuotraukos/@item.nuotraukos_nuoroda" data-lightbox="models" data-title="@item.nuotraukos_nuoroda">
                        <img class="customImg" src="~/Nuotraukos/@item.nuotraukos_nuoroda" />
                    </a>
                }
            </div>
        </div>
    }
    else
    {
        <p>Nuotraukų nebuvo pridėta</p>
    }
</div>
<div style="margin:2vh">
    <input type="submit" value="< Atgal" onclick="@("window.location.href='" + @Url.Action("Projektai", "Projektas") + "'");" class="btn btn-info" />
</div>

PVP_K180/Views/Projektas/ProjektoKurimas.cshtml
@model PVP_K180.ModelView.Projekto_duomenys

@{
    ViewBag.Title = "ProjektoKurimas";

    List<SelectListItem> listItems = new List<SelectListItem>();
    listItems.Add(new SelectListItem
    {
        Text = "Bus vykdomas",
        Value = "1"
    });
    listItems.Add(new SelectListItem
    {
        Text = "Pasibaigęs",
        Value = "2",
    });
    listItems.Add(new SelectListItem
    {
        Text = "Vykdomas",
        Value = "3"
    });
}
<script src="~/Themes/ckeditor/ckeditor.js"></script>


<style>
    .boxShadow {
        box-shadow: 0 1px 10px rgb(0 0 0 / 0.2);
        border-radius: 5px;
        width: 100%;
        padding: 10px;
        position: relative;
        background-color: white;
    }
</style>

@using (Html.BeginForm("ProjektoKurimas", "Projektas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div style="margin-top:20px" class="form-horizontal boxShadow">
    <h2>Kurti naują projektą</h2>
    @if (TempData["Fail"] != null)
    {
        <p class="alert alert-danger" id="successMessage">@Convert.ToString(TempData["Fail"])</p>
    }

    @if (TempData["Succ"] != null)
    {
        <p class="alert alert-success" id="successMessage">@Convert.ToString(TempData["Succ"])</p>
    }
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.projektas.pavadinimas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.projektas.pavadinimas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.projektas.pavadinimas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.projektas.aprasymas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.projektas.aprasymas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.projektas.aprasymas, "", new { @class = "text-danger" })
        </div>
    </div>
    <script>CKEDITOR.replace("projektas_aprasymas");</script>
    <div class="form-group">
        @Html.LabelFor(model => model.projektas.projekto_busena, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.projektas.projekto_busena, listItems, "-- Pasirinkite --")
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.nuotraukos, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.nuotraukos, "", new { @type = "file", @multiple = "multiple" })
            @Html.ValidationMessageFor(model => model.nuotraukos, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Sukurti" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div style="margin-top: 30px;">
    <input type="submit" value="< Atgal" onclick="@("window.location.href='" + @Url.Action("GautiProjektus") + "'");" class="btn btn-info" />
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")

}