PVP_K180/Models/Atsitikimas.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PVP_K180.Models;

namespace PVP_K180.Models
{
    public class Atsitikimas
    {
        [DisplayName("Atsitikimo id")]
        public int id_Atstikimas { get; set; }

        [DisplayName("Atsitikimo sukurimo data")]
        [DisplayFormat(DataFormatString = "{0:yyyy-MM-dd}", ApplyFormatInEditMode = true)]
        public DateTime paskelbimo_data { get; set; }

        [DisplayName("Aprašymas")]
        public string aprasymas { get; set; }

        public double zemelapio_ilguma { get; set; }
        public double zemelapio_platuma { get; set; }

        [DisplayName("Komentaras")]
        public string komentaras { get; set; }

        [DisplayName("Atsitikimo tipas")]
        [Required(ErrorMessage = "Privalo būti pasirinktas tipas")]
        public int atsitikimo_tipas { get; set; }
        public int atsitikimo_busena { get; set; }

        public int? fk_Vartotojasid_Tvirtintojas { get; set; }
        public int fk_Vartotojasid_Pranesejas { get; set; }

        [DisplayName("Tvirtintojas")]
        public string tvirtintojas { get; set; }
        [DisplayName("Pranešėjas")]
        public string pranesejas { get; set; }

        [DisplayName("Tipas")]
        public string tipas { get; set; }

        [DisplayName("Būsena")]
        public string busena { get; set; }

        public IList<SelectListItem> atsitikimo_tipai { get; set; }

        [DisplayName("Pridėti nuotraukas")]
        public HttpPostedFileBase[] nuotraukos { get; set; }
        public List<Nuotrauka> gautosNuotraukos { get; set; }
    }
}

PVP_K180/Controllers/AtsitikimasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PVP_K180.Models;
using PVP_K180.Repos;
using PVP_K180.ModelView;
using System.IO;
using PagedList;

namespace PVP_K180.Controllers
{
    public class AtsitikimasController : Controller
    {
        Atsitikimas_Repos atsitikimas_Repos = new Atsitikimas_Repos();
        Nuotrauka_Repos nuotrauka_Repos = new Nuotrauka_Repos();
        private const int pageSize = 5;
        public ActionResult SkelbtiAtsitikima()
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            Atsitikimas atsitikimas = new Atsitikimas();
            UzpildytiAtsitikimoTipus(atsitikimas);

            return View(atsitikimas);
        }

        [HttpPost]
        public ActionResult SkelbtiAtsitikima(Atsitikimas atsitikimas)
        {
            List<string> posiblesExtensions = new List<string>() { ".jpg", ".png", ".JPG", ".PNG", ".jpeg", ".JPEG" };

            UzpildytiAtsitikimoTipus(atsitikimas);
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Home");
            }

            if(atsitikimas.atsitikimo_tipas == 0)
            {
                TempData["AtsitikmasFail"] = "Turite Pasirinkti tipą";
                return View(atsitikimas);
            }

            if (Convert.ToDouble(TempData["AtsitikimasLang"]) == 0 || Convert.ToDouble(TempData["AtsitikimasLong"]) == 0)
            {
                TempData["AtsitikmasFail"] = "Turi būti pažymėta tiksli lokacija";
                return View(atsitikimas);
            }

            atsitikimas.paskelbimo_data = DateTime.Now;

            atsitikimas.fk_Vartotojasid_Pranesejas = Convert.ToInt32(Session["UserID"]);

            atsitikimas.zemelapio_ilguma = Convert.ToDouble(TempData["AtsitikimasLang"]);
            atsitikimas.zemelapio_platuma = Convert.ToDouble(TempData["AtsitikimasLong"]);
            atsitikimas.atsitikimo_busena = 1;

            atsitikimas_Repos.PridetiAtsitikima(atsitikimas);
            var lastIndex = atsitikimas_Repos.Gauti_Paskutini_Prideto_Index();

            TempData["AtsitikmasSuccsess"] = "Atsitikimas sėkmingai pridėtas";


            foreach (HttpPostedFileBase file in atsitikimas.nuotraukos)
            {
                if (file != null)
                {
                    var InputFileName = Path.GetFileName(file.FileName);

                    var extension = Path.GetExtension(file.FileName);
                    if (!posiblesExtensions.Contains(extension))
                    {
                        TempData["AtsitikmasFail"] = "Kai kurios nuotraukos įkeltus su netinkamu formatu";
                        continue;
                    }

                    var random = Guid.NewGuid() + InputFileName;
                    var ServerSavePath = Path.Combine(Server.MapPath("~/Nuotraukos/") + random);


                    file.SaveAs(ServerSavePath);
                    Nuotrauka nuotrauka = new Nuotrauka();
                    nuotrauka.nuotraukos_nuoroda = random;
                    nuotrauka.priskirtas_id = lastIndex;
                    nuotrauka_Repos.Prideti_Atsitikimo_Nuotraukas(nuotrauka);

                }
            }

            return View(atsitikimas);
        }

        public void UzpildytiAtsitikimoTipus(Atsitikimas atsitikimas)
        {
            var atsitikimai = atsitikimas_Repos.GautiAtsitikimoTipus();
            IList<SelectListItem> tipaiList = new List<SelectListItem>();
            foreach (var item in atsitikimai)
            {
                tipaiList.Add(new SelectListItem { Value = item.id_Atsitikimas_Tipas.ToString(), Text = item.name });
            }
            atsitikimas.atsitikimo_tipai = tipaiList;
        }

        [HttpPost]
        public void IsaugotiLokacija(float x, float y)
        {
            TempData["AtsitikimasLang"] = x;
            TempData["AtsitikimasLong"] = y;
        }


        public ActionResult AtsitikimuIstorija(int? busena,int? tipas, DateTime? nuo, DateTime? iki,int? page)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            List<Atsitikimas> atsitikimai = atsitikimas_Repos.GautiAtsitikimus();
            TempData["AdminMenu"] = false;
            if(busena != null)
            {
                atsitikimai = atsitikimai.Where(x => x.atsitikimo_busena == Convert.ToInt32(busena)).ToList();
            }
            if(tipas != null)
            {
                atsitikimai = atsitikimai.Where(x => x.atsitikimo_tipas == Convert.ToInt32(tipas)).ToList();
            }
            if (nuo != null)
            {
                var data = (DateTime)nuo;
                atsitikimai = atsitikimai.Where(x => x.paskelbimo_data.Date >= (DateTime)data.Date).ToList();
            }

            if (iki != null)
            {
                var data = (DateTime)iki;
                atsitikimai = atsitikimai.Where(x => x.paskelbimo_data.Date <= (DateTime)data.Date).ToList();
            }
            int pageNumber = (page ?? 1);
            return View(atsitikimai.Where(x=>x.fk_Vartotojasid_Pranesejas==Convert.ToInt32(Session["UserID"])).ToList().ToPagedList(pageNumber,pageSize));
        }

        public ActionResult AtsitikimuSarasas(int? busena, int? tipas, DateTime? nuo, DateTime? iki,int? page)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (!Session["Role"].Equals("Administratorius"))
            {
                return RedirectToAction("Index", "Home");
            }
            List<Atsitikimas> atsitikimai = atsitikimas_Repos.GautiAtsitikimus();
            TempData["AdminMenu"] = true;
            if (busena != null)
            {
                atsitikimai = atsitikimai.Where(x => x.atsitikimo_busena == Convert.ToInt32(busena)).ToList();
            }
            if (tipas != null)
            {
                atsitikimai = atsitikimai.Where(x => x.atsitikimo_tipas == Convert.ToInt32(tipas)).ToList();
            }
            if (nuo != null)
            {
                var data = (DateTime)nuo;
                atsitikimai = atsitikimai.Where(x => x.paskelbimo_data.Date >= (DateTime)data.Date).ToList();
            }

            if (iki != null)
            {
                var data = (DateTime)iki;
                atsitikimai = atsitikimai.Where(x => x.paskelbimo_data.Date <= (DateTime)data.Date).ToList();
            }
            int pageNumber = (page ?? 1);
            return View(atsitikimai.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult DetaliInformacija(int id)
        {
            Atsitikimas atsitikimas = atsitikimas_Repos.Gauti_Atsitikima(id);
            atsitikimas.gautosNuotraukos = nuotrauka_Repos.Gauti__Atsitikimu_Nuotraukas(id);
            return View(atsitikimas);
        }

        public ActionResult KeistiAtsitikimoBusena(int id)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (!Session["Role"].Equals("Administratorius"))
            {
                return RedirectToAction("Index", "Home");
            }
            TempData["idAtsitikimas"] = id;
            AtsitikimuKeitimasPerziura atsitikimas = atsitikimas_Repos.Gauti_Atsitikimo_Perziura(id);
            UzpildytiAtsitikimoBusenas(atsitikimas);
            
            return View(atsitikimas);
        }

        [HttpPost]
        public ActionResult KeistiAtsitikimoBusena(AtsitikimuKeitimasPerziura atsitikimas)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (!Session["Role"].Equals("Administratorius"))
            {
                return RedirectToAction("Index", "Home");
            }
            atsitikimas.tvirtintojas = Convert.ToInt32(Session["UserID"]);
            atsitikimas.id_Atstikimas = Convert.ToInt32(TempData["idAtsitikimas"]);
            atsitikimas_Repos.Atnaujinti_Atsitikimo_Busena(atsitikimas);
            UzpildytiAtsitikimoBusenas(atsitikimas);
            TempData["SuccsessAtstikimas"] = "Atsitikimas sėkmingai atnaujintas";   
            return View(atsitikimas);
        }

        public void UzpildytiAtsitikimoBusenas(AtsitikimuKeitimasPerziura atsitikimas)
        {
            var atsitikimai = atsitikimas_Repos.GautiAtsitikimoBusenas();
            IList<SelectListItem> busenosList = new List<SelectListItem>();
            foreach (var item in atsitikimai)
            {
                busenosList.Add(new SelectListItem { Value = item.id_Atsitikimas_Busena.ToString(), Text = item.name });
            }
            atsitikimas.atsitikimo_busenos = busenosList;
        }

    }
}

PVP_K180/Views/Atsitikimas/DetaliInformacija.cshtml
@model PVP_K180.Models.Atsitikimas

@{
    ViewBag.Title = "DetaliInformacija";
}

<link href="~/Styles/photoStyle.css" rel="stylesheet" />
<link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
      integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
      crossorigin="" />
<link href="~/Styles/lightbox.css" rel="stylesheet" />
<script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
        integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=="
        crossorigin=""></script>
<style>
    #map {
        height: 580px;
    }

    .marker-position {
        position: absolute;
        bottom: 0;
        left: 0;
        z-index: 999;
        padding: 10px;
        font-weight: 700;
        background-color: #fff;
    }

    .mapStyle {
        position: relative;
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji";
        min-height: 100%;
        margin: 0;
        padding: 0;
        background-color: #f1f1f1;
        margin-top:20px;
    }
</style>

<style>
    .boxShadow {
        box-shadow: 0 1px 10px rgb(0 0 0 / 0.2);
        margin: auto;
        border-radius: 5px;
        background-color:white;
        width: 75%;
        text-align: center;
        padding: 10px;
        margin-top: 30px;
        position: relative;
        word-wrap: break-word;
    }
</style>

<h2 style="text-align:center">Detali informacija</h2>

<div>

    <div class="boxShadow">
        <p style="text-align:left;font-size:20px; font-weight:bold">
            Atsitikimas #@Model.id_Atstikimas
            @if (Session["Role"].Equals("Administratorius"))
            {
            <span style="float:right;">
                @Html.ActionLink("Atnaujinti atsitikimą", "KeistiAtsitikimoBusena", "Atsitikimas", new { id = Model.id_Atstikimas }, new { @class = "lnkGetReward btn btn-default btn-sm" })
            </span>
            }
        </p>
        <hr />
        <p style="text-align:left">
            Atsitikimo tipas: <b>@Model.tipas</b>
            <span style="float:right;">
                Atsitikimo būsena: <b>@Model.busena</b>
            </span>
        </p>
    </div>

    <div class="boxShadow" style="text-align:left;font-size:15px;">
        <p style="text-align: left; font-size: 20px; font-weight: bold">@Html.DisplayNameFor(model => model.aprasymas)</p>
        <hr />
        <p>@Html.DisplayFor(model => model.aprasymas)</p>
    </div>

    <div class="boxShadow" style="text-align:left;font-size:15px;">
        <p style="text-align: left; font-size: 20px; font-weight: bold">@Html.DisplayNameFor(model => model.komentaras)</p>
        <hr />
        <p> @Html.DisplayFor(model => model.komentaras)</p>
    </div>

    <div class="boxShadow" style="text-align:left;font-size:15px;">
        <p style="text-align: left; font-size: 20px; font-weight: bold">@Html.DisplayNameFor(model => model.pranesejas)</p>
        <hr />
        <p>@Html.DisplayFor(model => model.pranesejas)</p>
    </div>

    <div class="boxShadow" style="text-align:left;font-size:15px;">
        <p style="text-align: left; font-size: 20px; font-weight: bold"> @Html.DisplayNameFor(model => model.tvirtintojas)</p>
        <hr />
        <p> @Html.DisplayFor(model => model.tvirtintojas)</p>
    </div>

    <div class="boxShadow">
        <p style="text-align: left; font-size: 20px; font-weight: bold">Lokacija</p>
        <hr />
        <div class="mapStyle">

            <div id="map"></div>
        </div>
    </div>

    <script src="~/Scripts/lightbox.js"></script>
    <div class="boxShadow">

        <p style="text-align: left; font-size: 20px; font-weight: bold">Nuotraukos</p>
        <hr />
        @if (Model.gautosNuotraukos.Count != 0)
        {
            <div class="containerPhoto">
                <div class="gallery">
                    @foreach (var item in Model.gautosNuotraukos)
                    {
                        <a href="~/Nuotraukos/@item.nuotraukos_nuoroda" data-lightbox="models" data-title="@item.nuotraukos_nuoroda">
                            <img src="~/Nuotraukos/@item.nuotraukos_nuoroda" />
                        </a>
                    }
                </div>
            </div>
        }
        else
        {
            <p>Nuotraukų nebuvo pridėta</p>
        }

    </div>
</div>
<p style="margin-top:20px">
    @if (Convert.ToBoolean(TempData["AdminMenu"]) == true)
    {
        <div style="margin-left:9vh">
            <input type="submit" value="< Atgal" onclick="@("window.location.href='" + @Url.Action("AtsitikimuSarasas") + "'");" class="btn btn-info" />
        </div>

    }
    else
    {
        <div style="margin-left:9vh">
            <input type="submit" value="< Atgal" onclick="@("window.location.href='" + @Url.Action("AtsitikimuIstorija") + "'");" class="btn btn-info" />
        </div>
    }

</p>


<script>

    /* eslint-disable no-undef */
    /**
     * add move and delete marker
     */

    // config map
    let config = {
        minZoom: 3,
        maxZoom: 18,
    };
    // magnification with which the map will start
    const zoom = 15;
    // co-ordinates
    const lat = '@Model.zemelapio_ilguma'.replace(",", ".");
    const lng = '@Model.zemelapio_platuma'.replace(",", ".");

    // calling map
    const map = L.map("map", config).setView([lat, lng], zoom);
    var main = L.marker([lat, lng]).addTo(map).bindPopup('@Model.tipas');

    // Used to load and display tile layers on the map
    // Most tile servers require attribution, which you can set under `Layer`
    L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png", {
        attribution:
            '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors',
    }).addTo(map);

</script>

PVP_K180/Views/Atsitikimas/KeistiAtsitikimoBusena.cshtml
@model PVP_K180.ModelView.AtsitikimuKeitimasPerziura

@{
    ViewBag.Title = "Atsitikimų būsenos keitimas";
}

<h2>Atstitikimo būsenos keitimas</h2>

@if (TempData["SuccsessAtstikimas"] != null)
{
    <p class="alert alert-success" id="successMessage">@Convert.ToString(TempData["SuccsessAtstikimas"])</p>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />

        <div class="form-group">
            @Html.LabelFor(model => model.atsitikimo_busena, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.atsitikimo_busena, Model.atsitikimo_busenos, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.atsitikimo_busenos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.komentaras, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.komentaras, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.komentaras, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Atnauninti" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Atgal", "DetaliInformacija", new { id = Model.id_Atstikimas })
</div>

PVP_K180/Views/Atsitikimas/SkelbtiAtsitikima.cshtml
@model PVP_K180.Models.Atsitikimas

@{
    ViewBag.Title = "Skelbti Atsitikima";
}

<link rel="stylesheet" href="https://unpkg.com/leaflet@1.8.0/dist/leaflet.css"
      integrity="sha512-hoalWLoI8r4UszCkZ5kL8vayOGVae1oxXe/2A4AO6J9+580uKHDO3JdHb7NzwwzK5xr/Fs0W40kiNHxM9vyTtQ=="
      crossorigin="" />
<script src="https://unpkg.com/leaflet@1.8.0/dist/leaflet.js"
        integrity="sha512-BB3hKbKWOc9Ez/TAwyWxNXeoV9c1v6FIeYiBieIWkpLjauysF18NzgR1MBNBXf8/KABdlkX68nAhlwcDFLGPCQ=="
        crossorigin=""></script>
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/font-awesome@4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/leaflet.locatecontrol@v0.76.0/dist/L.Control.Locate.min.css" />

<style>
    body {
        margin: 0;
        padding: 0;
    }

    #map {
        height: 70vh;

    }

    .marker-position {
        position: absolute;
        bottom: 0;
        left: 0;
        z-index: 999;
        padding: 10px;
        font-weight: 700;
        background-color: #fff;
    }

    .mapStyle {
        position: relative;
        font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif, "Apple Color Emoji", "Segoe UI Emoji";
        min-height: 0;
        margin: 0;
        padding: 0;
        background-color: #f1f1f1;
    }

    .boxShadow {
        box-shadow: 0 1px 10px rgb(0 0 0 / 0.2);
        border-radius: 5px;
        width: 100%;
        padding: 10px;
        position: relative;
        background-color: white;
    }
</style>


@using (Html.BeginForm("SkelbtiAtsitikima", "Atsitikimas", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div style="margin-top:20px" class=" boxShadow form-horizontal">
    <h4>Atsitikimo suvestinė</h4>
    <hr />
    @if (TempData["AtsitikmasFail"] != null)
    {
        <p class="alert alert-danger" id="successMessage">@Convert.ToString(TempData["AtsitikmasFail"])</p>
    }

    @if (TempData["AtsitikmasSuccsess"] != null)
    {
        <p class="alert alert-success" id="successMessage">@Convert.ToString(TempData["AtsitikmasSuccsess"])</p>
    }
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.atsitikimo_tipas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.atsitikimo_tipas, Model.atsitikimo_tipai, "---Pasirinkite tipą---", new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.atsitikimo_tipai, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.aprasymas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.aprasymas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.aprasymas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.nuotraukos, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.nuotraukos, "", new { @type = "file", @multiple = "multiple" })
            @Html.ValidationMessageFor(model => model.nuotraukos, "", new { @class = "text-danger" })
        </div>
    </div>
    <div style="display:flex;flex-direction:column;align-content:space-around;flex-wrap:wrap">
        <p style="text-align:center;font-weight:bold">Pasirinkite vietą, kurioje yra įvykis</p>
        <div style="width:75%" class=" boxShadow mapStyle">
            <div class="marker-position">Paspauskite ant žemėlapio</div>
            <div id="map"></div>
        </div>
    </div>

    <div style="display: flex; flex-direction: column; align-content: space-around; flex-wrap: wrap">
        <div style="margin-top:10px" class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Paskelbti" class="btn btn-default" />
            </div>
        </div>
    </div>

</div>
}

<div style="margin-top:20px;margin-bottom:10px;">
    <input type="submit" value="< Atgal" onclick="@("window.location.href='" + @Url.Action("ProfilioValdymas", "Vartotojas") + "'");" class="btn btn-info" />
</div>

<script src="https://cdn.jsdelivr.net/npm/leaflet.locatecontrol@0.76.0/dist/L.Control.Locate.min.js" charset="utf-8"></script>
<script>

    var arGaliPrideti = true;

    let config = {
        minZoom: 3,
        maxZoom: 18,
    };

    const zoom = 18;

    const lat = 54.905545;
    const lng = 23.961254;
    // Map initialization 
    var map = L.map('map').setView([lat, lng], 8);

    var saveLat = 0;
    var saveLng = 0;

    //osm layer
    var osm = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
        attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
    });
    osm.addTo(map);


    map.on("click", addMarker);

    function saveData() {

        console.log(saveLng);
        $.post("/Atsitikimas/IsaugotiLokacija", { x: saveLat, y: saveLng });
    }

    function addMarker(e) {
        // Add marker to map at click location
        if (arGaliPrideti == false) {
            const markerPlace = document.querySelector(".marker-position");
            markerPlace.textContent = `Gali būti tik vienas pridėtas markeris vienu metu`;
            return;
        } else {
            arGaliPrideti = false;
        }
        saveLat = e.latlng.lat;
        saveLng = e.latlng.lng;
        const markerPlace = document.querySelector(".marker-position");
        markerPlace.textContent = `Naujas markeris: ${e.latlng.lat}, ${e.latlng.lng}`;

        const marker = new L.marker(e.latlng, {
            draggable: true,
        })
            .addTo(map)
            .bindPopup(buttonRemove);

        // event remove marker
        marker.on("popupopen", removeMarker);

        // event draged marker
        marker.on("dragend", dragedMaker);

        $.post("/Atsitikimas/IsaugotiLokacija", { x: saveLat, y: saveLng });
    }

    const buttonRemove =
        '<button type="button" class="remove">Ištrinti</button>';

    const markerPlace = document.querySelector(".marker-position");

    // remove marker
    function removeMarker() {
        const marker = this;
        const btn = document.querySelector(".remove");
        btn.addEventListener("click", function () {
            markerPlace.textContent = "Markeris ištrintas";
            map.removeLayer(marker);
            arGaliPrideti = true;
            saveLat = 0;
            saveLng = 0;
        });
    }

    // draged
    function dragedMaker() {
        markerPlace.textContent = `Pakeista pozicija: ${this.getLatLng().lat}, ${this.getLatLng().lng
            }`;
        saveLat = this.getLatLng().lat;
        saveLng = this.getLatLng().lng;
        $.post("/Atsitikimas/IsaugotiLokacija", { x: saveLat, y: saveLng });
    }



    L.control.locate({
        showPopup: true,
        position: 'topleft',
        strings: {
            metersUnit: "metrai",
            feetUnit: "pėdos",
            title: "Mano lokacija",
            popup: "Tu randies {distance} {unit} nuo šito taško",
        },
    }).addTo(map);
</script>