PVP_K180/Models/Naujiena.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PVP_K180.Models
{
    public class Naujiena
    {
        [DisplayName("Naujienos ID")]
        public int id_Naujiena { get; set; }

        [DisplayName("Pavadinimas")]
        [Required(ErrorMessage = "Privalo būti įvestas pavadinimas")]
        public string pavadinimas { get; set; }

        [DisplayName("Naujienos tekstas")]
        [AllowHtml]
        [Required(ErrorMessage = "Privalo būti įvestas naujienos tekstas")]
        public string naujienos_tekstas { get; set; }

        [DisplayName("Naujienos sukurimo data")]
        [DisplayFormat(DataFormatString = "{0:yyyy-dd-MM}", ApplyFormatInEditMode = true)]
        public DateTime naujienos_sukurimo_data { get; set; }

        [DisplayName("Sukurta vartotojo")]
        public int naujienos_kurejo_ID { get; set; }



        public List<Nuotrauka> nuotraukos { get; set; }
    }
}

PVP_K180/Controllers/NaujienaController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;
using PagedList;
using PVP_K180.Models;
using PVP_K180.ModelView;
using PVP_K180.Repos;

namespace PVP_K180.Controllers
{
    public class NaujienaController : Controller
    {
        Naujiena naujiena = new Naujiena();
        Naujiena_Repos naujiena_Repos = new Naujiena_Repos();
        Nuotrauka_Repos nuotrauka_Repos = new Nuotrauka_Repos();
        string[] menesiai = new string[12] { "Sausis", "Vasaris", "Kovas", "Balandis", "Gegužis", "Bižrelis", "Liepa", "Lapkritis", "Rugsėjis", "Spalis", "Lapkritis", "Gruodis" };
        private const int pageSize = 5;
        private const int pageSizeNewsView = 10;

        // GET: Naujiena
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult NaujienosKurimas()
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (!Session["Role"].Equals("Administratorius"))
            {
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        [HttpPost]
        public ActionResult NaujienosKurimas(Naujienos_duomenys naujienos_Duomenys)
        {
            List<string> posiblesExtensions = new List<string>() { ".jpg", ".png", ".JPG", ".PNG", ".jpeg", ".JPEG" };
            Naujiena_Repos naujiena_Repos = new Naujiena_Repos();
            naujienos_Duomenys.naujiena.naujienos_kurejo_ID = (int)Session["UserID"];
            naujienos_Duomenys.naujiena.naujienos_sukurimo_data = DateTime.Now;
            bool flag = naujiena_Repos.Sukurti_Naujiena(naujienos_Duomenys.naujiena);
            if (flag)
            {
                int lastIndex = naujiena_Repos.Gauti_Paskutini_Prideto_Index();

                foreach(HttpPostedFileBase file in naujienos_Duomenys.nuotraukos)
                {
                    if (file != null)
                    {
                        var InputFileName = Path.GetFileName(file.FileName);

                        var extension = Path.GetExtension(file.FileName);
                        if (!posiblesExtensions.Contains(extension))
                        {
                            TempData["Fail"] = "Įkeltas su netinkamu formatu";
                            return View();
                        }

                        var random = Guid.NewGuid() + InputFileName;
                        var ServerSavePath = Path.Combine(Server.MapPath("~/Nuotraukos/") + random);


                        file.SaveAs(ServerSavePath);
                        Nuotrauka nuotrauka = new Nuotrauka();
                        nuotrauka.nuotraukos_nuoroda = random;
                        nuotrauka.priskirtas_id = lastIndex;
                        nuotrauka_Repos.Prideti_Naujienos_Nuotraukas(nuotrauka);

                    }
                }
                TempData["Succ"] = "Naujiena sėkmingai sukurta!";
               
            }
            else
            {
                TempData["Fail"] = "Naujiena nesukurta!";

            }
            return View();
        }

        public ActionResult GautiNaujienas(int? page)
        {

            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (!Session["Role"].Equals("Administratorius"))
            {
                return RedirectToAction("Index", "Home");
            }
            if (Session["Message"] != null)
            {
                if (Convert.ToBoolean(Session["Message"]))
                {
                    Response.Write("<script type='text/javascript' language='javascript'> alert('Nuotrauka pridėta sėkmingai!')</script>");
                    Session.Remove("Message");
                }
                else
                {
                    Response.Write("<script type='text/javascript' language='javascript'> alert('Nuotrauka pridėta nesėkmingai!')</script>");
                    Session.Remove("Message");      
                }
            }
            Naujiena_Repos naujiena_Repos = new Naujiena_Repos();
            List<Naujiena> naujienos = naujiena_Repos.Gauti_Naujienas();
            int pageNumber = (page ?? 1);
            return View(naujienos.ToPagedList(pageNumber, pageSize));
        }

        public ActionResult GautiNuotraukas(int id)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (!Session["Role"].Equals("Administratorius"))
            {
                return RedirectToAction("Index", "Home");
            }

            Nuotrauka_Repos nuotrauka_Repos = new Nuotrauka_Repos();
            List<Nuotrauka> nuotraukos = nuotrauka_Repos.Gauti__Naujienu_Nuotraukas(id);
            foreach (var item in nuotraukos)
            {
                var path = Path.Combine(("/Nuotraukos/") + item.nuotraukos_nuoroda);
                item.nuotraukos_nuoroda = path;
            }

            return View(nuotraukos);

        }


        public ActionResult TrintiNaujiena(int id)
        {
            Naujiena_Repos naujiena_Repos = new Naujiena_Repos();
            bool flag = naujiena_Repos.Trinti_Naujiena(id);
            return RedirectToAction("GautiNaujienas");
        }

        public ActionResult TrintiNuotrauka(int id)
        {
            Nuotrauka_Repos nuotrauka_Repos = new Nuotrauka_Repos();
            Nuotrauka nuotrauka = nuotrauka_Repos.Gauti_Nuotrauka(id);
            var ServerSavePath = Path.Combine(Server.MapPath("~/Nuotraukos/") + nuotrauka.nuotraukos_nuoroda);
            if (System.IO.File.Exists(ServerSavePath))
            {
                System.IO.File.Delete(ServerSavePath);
                bool flag = nuotrauka_Repos.Trinti_Nuotrauka(id);
            }
            return RedirectToAction("GautiNuotraukas", new { id = nuotrauka.priskirtas_id });
        }

        public ActionResult RedaguotiNaujiena(int id)
        {
            Naujiena_Repos naujiena_Repos = new Naujiena_Repos();
            naujiena = naujiena_Repos.Gauti_Naujiena(id);
            TempData["naujienosID"] = id;
            return View(naujiena);
        }

        [HttpPost]
        public ActionResult RedaguotiNaujiena(int? naujienosID, Naujiena naujiena)
        {
            Naujiena_Repos naujiena_Repos = new Naujiena_Repos();
            naujiena.id_Naujiena = Convert.ToInt32(TempData["naujienosID"]);
            naujiena.naujienos_kurejo_ID = (int)Session["UserID"];
            naujiena.naujienos_sukurimo_data = DateTime.Now;
            bool flag = naujiena_Repos.Redaguoti_Naujiena(naujiena);
            if (flag)
            {
                TempData["Succ"] = "Naujiena sėkmingai redaguota!";
            }
            else
            {
                TempData["Fail"] = "Naujiena neredaguota!";

            }
            TempData["naujienosID"] = naujiena.id_Naujiena;
            return View(naujiena);
        }

        public ActionResult PridetiNuotrauku(int id)
        {
            if (Session["UserID"] == null)
            {
                return RedirectToAction("Index", "Home");
            }
            else if (!Session["Role"].Equals("Administratorius"))
            {
                return RedirectToAction("Index", "Home");
            }

            Nuotrauku_Duomenys nuotrauku_Duomenys = new Nuotrauku_Duomenys();
            Session["NaujienosID"] = id;
            return View(nuotrauku_Duomenys);
        }

        [HttpPost]
        public ActionResult PridetiNuotrauku(Nuotrauku_Duomenys nuotrauku_Duomenys)
        {
            List<string> posiblesExtensions = new List<string>() {".jpg", ".png", ".JPG", ".PNG", ".jpeg", ".JPEG"};
            nuotrauku_Duomenys.priskirtas_id = Convert.ToInt32(Session["NaujienosID"]);
            Session.Remove("NaujienosID");

            int photoCount = 0;
            foreach (HttpPostedFileBase file in nuotrauku_Duomenys.nuotraukos)
            {
                if (file != null)
                {
                    photoCount++;
                    var InputFileName = Path.GetFileName(file.FileName);
                    var extension = Path.GetExtension(file.FileName);

                    if(!posiblesExtensions.Contains(extension))
                    {
                        TempData["Fail"] = "Įkeltas su netinkamu formatu";
                        return View();
                    }

                    var random = Guid.NewGuid() + InputFileName;
                    var ServerSavePath = Path.Combine(Server.MapPath("~/Nuotraukos/") + random);


                    file.SaveAs(ServerSavePath);
                    Nuotrauka nuotrauka = new Nuotrauka();
                    nuotrauka.nuotraukos_nuoroda = random;
                    nuotrauka.priskirtas_id = nuotrauku_Duomenys.priskirtas_id;
                    nuotrauka_Repos.Prideti_Naujienos_Nuotraukas(nuotrauka);
                }
            }

            if(photoCount == 0)
            {
                Session["Message"] = false;
            }
            else
            {
                Session["Message"] = true;
            }

            return RedirectToAction("GautiNaujienas");
        }

        public ActionResult Naujienos(int? page)
        {
            List<Naujiena> naujienos = naujiena_Repos.Gauti_Naujienas();
            List<NaujienuSarasas> naujienosPerziurai = new List<NaujienuSarasas>();

            foreach(var item in naujienos)
            {
                NaujienuSarasas naujiena = new NaujienuSarasas();

                naujiena.naujienos_id = item.id_Naujiena;
                naujiena.naujienos_antraste = item.pavadinimas;
                List<Nuotrauka> nuotraukos = nuotrauka_Repos.Gauti__Naujienu_Nuotraukas(naujiena.naujienos_id);

PVP_K180/Views/Naujiena/GautiNaujienas.cshtml
@model PagedList.IPagedList<PVP_K180.Models.Naujiena>
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = "Naujienų sąrašas";
}
@Styles.Render("~/Styles/tableStyle.css")
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
    $(document).ready(function () {
        $("#myInput").on("keyup", function () {
            var value = $(this).val().toLowerCase();
            $("#myTable tr").filter(function () {
                $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
            });
        });
    });
</script>
<h2>Naujienų sąrašas</h2>
<input id="myInput" type="text" placeholder="Įveskit pagal ką filtruosit">
<br>
<br>
<p>
    @Html.ActionLink("Sukurti naujieną", "NaujienosKurimas", new { }, new { @class = "btn btn-primary", @type = "button" })
</p>
<table class="table-fill">
    <thead>
        <tr>
            <th class="text-left">
                @Html.DisplayNameFor(model => model.FirstOrDefault().id_Naujiena)
            </th>
            <th class="text-left">
                @Html.DisplayNameFor(model => model.FirstOrDefault().pavadinimas)
            </th>
            <th class="text-left">
                @Html.DisplayNameFor(model => model.FirstOrDefault().naujienos_sukurimo_data)
            </th>
            <th>Funkcijos</th>
        </tr>
    </thead>

    <tbody class="table-hover" , id="myTable">
        @foreach (var item in Model)
        {
            <tr>
                <td class="text-left">
                    @Html.DisplayFor(modelItem => item.id_Naujiena)
                </td>
                <td class="text-left">
                    @Html.DisplayFor(modelItem => item.pavadinimas)
                </td>
                <td class="text-left">
                    @item.naujienos_sukurimo_data.ToString("yyyy-MM-dd")
                </td>
                <td class="text-left">
                    @Html.ActionLink("Redaguoti", "RedaguotiNaujiena", new { id = item.id_Naujiena }) |
                    @Html.ActionLink("Pašalinti", "TrintiNaujiena", new { id = item.id_Naujiena }) |
                    @Html.ActionLink("Pridėti nuotraukų", "PridetiNuotrauku", new { id = item.id_Naujiena }) |
                    @Html.ActionLink("Nuotraukos", "GautiNuotraukas", new { id = item.id_Naujiena })
                </td>
            </tr>
        }
    </tbody>
</table>

<div id="pager">
    @Html.PagedListPager(Model, page => Url.Action("GautiNaujienas", new { page }))
</div>

<div style="margin-top:30px;">
    <input type="submit" value="< Atgal" onclick="@("window.location.href='" + @Url.Action("AdminValdymas", "Vartotojas") + "'");" class="btn btn-info" />
</div>

PVP_K180/Views/Naujiena/GautiNuotraukas.cshtml
@model IEnumerable<PVP_K180.Models.Nuotrauka>

@{
    ViewBag.Title = "GautiNuotraukas";
}


<style>
    .boxShadow {
        box-shadow: 0 1px 10px rgb(0 0 0 / 0.2);
        border-radius: 5px;
        width: 100%;
        padding: 10px;
        position: relative;
        background-color: white;
    }

    .img{
        max-width:200px;
        max-height:200px;
    }
</style>

<div style="margin-top:20px" class="boxShadow">

    <h2>Nuotraukų sąrašas</h2>


    <table class="table">
        <tr>
            <th>
                Nuotrauka
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    <img class="img" src="@(item.nuotraukos_nuoroda)" />
                </td>
                <td>
                    @Html.ActionLink("Ištrinti", "TrintiNuotrauka", new { id = item.id_Nuotrauka }, new { @class = "btn btn-danger" })
                </td>
            </tr>

        }


    </table>
</div>
<div style="margin-top: 30px;">
    <input type="submit" value="< Atgal" onclick="@("window.location.href='" + @Url.Action("GautiNaujienas") + "'");" class="btn btn-info" />
</div>

PVP_K180/Views/Naujiena/Index.cshtml
@model PVP_K180.ModelView.Naujienos_duomenys

@{
    ViewBag.Title = "NaujienosKurimas";
}

<h2>NaujienosKurimas</h2>

@using (Html.BeginForm("NaujienosKurimas", "Naujiena", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Naujiena</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })


        <div class="form-group">
            @Html.LabelFor(model => model.naujiena.pavadinimas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.naujiena.pavadinimas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.naujiena.pavadinimas, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.naujiena.naujienos_tekstas, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.naujiena.naujienos_tekstas, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.naujiena.naujienos_tekstas, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.nuotraukos, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.nuotraukos, "", new { @type = "file", @multiple = "multiple" })
                @Html.ValidationMessageFor(model => model.nuotraukos, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "GautiNaujienas")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script> 

PVP_K180/Views/Naujiena/Naujienos.cshtml
@model PagedList.IPagedList<PVP_K180.ModelView.NaujienuSarasas>
@using PagedList;
@using PagedList.Mvc;
@{
    ViewBag.Title = "Naujienos";
}


@Styles.Render("~/Styles/cardNews.css")

<link href="~/Styles/newsStyle2.0.css" rel="stylesheet" />


<style>
    .content {
        max-width: 500px;
        margin: auto;
    }
</style>
<header>
    <h1>Seniūnijos naujienos</h1>
</header>
<div class="band">
    <div class="item-1">
        <a href="@(@Url.Action("SkaitytiNaujiena", "Naujiena", new { id = Model.First().naujienos_id }))" class="card">
            <div class="thumb" style="background-image: url(../../Nuotraukos/@Model.First().pirma_nuotrauka)"></div>
            <article>
                <h1>@Model.First().naujienos_antraste</h1>
                <span>@Model.First().menesioPav @Model.First().data.Day</span>
            </article>
        </a>
    </div>

    @for (var i = 1; i < Model.Count(); i++)
    {
        <div class="item-2">
            <a href="@(@Url.Action("SkaitytiNaujiena", "Naujiena", new { id = Model.ElementAt(i).naujienos_id }))" class="card">
                <div class="thumb" style="background-image: url(../../Nuotraukos/@Model.ElementAt(i).pirma_nuotrauka);"></div>
                <article>
                    <h1>@Model.ElementAt(i).naujienos_antraste</h1>
                    <p>@Html.Raw(Model.ElementAt(i).trumpasAprasas)</p>
                    <span>@Model.ElementAt(i).menesioPav @Model.ElementAt(i).data.Day</span>
                </article>
            </a>
        </div>
    }
</div>


<div id="pager" style="text-align:center">
    @Html.PagedListPager(Model, page => Url.Action("Naujienos", new { page }))
</div>

<div class="row" style="margin-top:2vh;margin-left:50px;margin-bottom:10px; float:left">
    <input type="submit" value="< Atgal" onclick="@("window.location.href='" + @Url.Action("Index", "Home") + "'");" class="btn btn-info" />
</div>

PVP_K180/Views/Naujiena/NaujienosKurimas.cshtml
@model PVP_K180.ModelView.Naujienos_duomenys

@{
    ViewBag.Title = "NaujienosKurimas";
}

<style>
    .boxShadow {
        box-shadow: 0 1px 10px rgb(0 0 0 / 0.2);
        border-radius: 5px;
        width: 100%;
        padding: 10px;
        position: relative;
        background-color: white;
    }
</style>

<script src="~/Themes/ckeditor/ckeditor.js"></script>


@using (Html.BeginForm("NaujienosKurimas", "Naujiena", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div style="margin-top:20px" class="boxShadow form-horizontal">
    <h2>Naujienos kurimas</h2>
    @if (TempData["Fail"] != null)
    {
        <p class="alert alert-danger" id="successMessage">@Convert.ToString(TempData["Fail"])</p>
    }

    @if (TempData["Succ"] != null)
    {
        <p class="alert alert-success" id="successMessage">@Convert.ToString(TempData["Succ"])</p>
    }
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.naujiena.pavadinimas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.naujiena.pavadinimas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.naujiena.pavadinimas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.naujiena.naujienos_tekstas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.naujiena.naujienos_tekstas, new { htmlAttributes = new { @class = "form-control" } })
            <script>CKEDITOR.replace("naujiena_naujienos_tekstas");</script>
            @Html.ValidationMessageFor(model => model.naujiena.naujienos_tekstas, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.nuotraukos, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.nuotraukos, "", new { @type = "file", @multiple = "multiple" })
            @Html.ValidationMessageFor(model => model.nuotraukos, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Sukurti" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div style="margin:2vh">
    <input type="submit" value="< Atgal" onclick="@("window.location.href='" + @Url.Action("GautiNaujienas") + "'");" class="btn btn-info" />
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script> 

PVP_K180/Views/Naujiena/PridetiNuotrauku.cshtml
@model PVP_K180.ModelView.Nuotrauku_Duomenys

@{
    ViewBag.Title = "Nuotraukų pridėjimas";
}


<style>
    .boxShadow {
        box-shadow: 0 1px 10px rgb(0 0 0 / 0.2);
        border-radius: 5px;
        width: 100%;
        padding: 10px;
        position: relative;
        background-color: white;
    }
</style>




@using (Html.BeginForm("PridetiNuotrauku", "Naujiena", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div style="margin-top:20px" class="boxShadow form-horizontal">
    <h2>Pridėti nuotraukas</h2>
    @if (TempData["Fail"] != null)
    {
        <p class="alert alert-danger" id="successMessage">@Convert.ToString(TempData["Fail"])</p>
    }

    @if (TempData["Succ"] != null)
    {
        <p class="alert alert-success" id="successMessage">@Convert.ToString(TempData["Succ"])</p>
    }

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })


    <div class="form-group">
        @Html.LabelFor(model => model.nuotraukos, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextBoxFor(model => model.nuotraukos, "", new { @type = "file", @multiple = "multiple" })
            @Html.ValidationMessageFor(model => model.nuotraukos, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Išsaugoti" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div style="margin-top: 30px;">
    <input type="submit" value="< Atgal" onclick="@("window.location.href='" + @Url.Action("GautiNaujienas", "Naujiena") + "'");" class="btn btn-info" />
</div>

PVP_K180/Views/Naujiena/RedaguotiNaujiena.cshtml
@model PVP_K180.Models.Naujiena

@{
    ViewBag.Title = "Redaguoti naujieną";
}
<script src="~/Themes/ckeditor/ckeditor.js"></script>


<style>
    .boxShadow {
        box-shadow: 0 1px 10px rgb(0 0 0 / 0.2);
        border-radius: 5px;
        width: 100%;
        padding: 10px;
        position: relative;
        background-color: white;
    }
</style>



@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div style="margin-top:20px" class="boxShadow form-horizontal">
    <h2>Redaguoti naujieną</h2>
    @if (TempData["Fail"] != null)
    {
        <p class="alert alert-danger" id="successMessage">@Convert.ToString(TempData["Fail"])</p>
    }

    @if (TempData["Succ"] != null)
    {
        <p class="alert alert-success" id="successMessage">@Convert.ToString(TempData["Succ"])</p>
    }

    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

    <div class="form-group">
        @Html.LabelFor(model => model.pavadinimas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.pavadinimas, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.pavadinimas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.naujienos_tekstas, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.TextAreaFor(model => model.naujienos_tekstas, new { htmlAttributes = new { @class = "form-control" } })
            <script>CKEDITOR.replace("naujienos_tekstas");</script>
            @Html.ValidationMessageFor(model => model.naujienos_tekstas, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Išsaugoti" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div style="margin-top: 30px;">
    <input type="submit" value="< Atgal" onclick="@("window.location.href='" + @Url.Action("GautiNaujienas") + "'");" class="btn btn-info" />
</div>

PVP_K180/Views/Naujiena/SkaitytiNaujiena.cshtml
@model PVP_K180.Models.Naujiena

@{
    ViewBag.Title = Model.pavadinimas;
}

<script src="~/Scripts/lightbox.js"></script>
<link href="~/Styles/lightbox.css" rel="stylesheet" />

<style>
    .boxShadow2 {
        box-shadow: 0 1px 5px rgb(0 0 0 / 0.2);
        margin: auto;
        border-radius: 4px;
        width: 100%;
        padding: 10px;
        margin-top: 30px;
        position: relative;
        background-color:white;
    }
    .customImg{
        max-height:200px;
        max-width:300px;
        padding-top:1vh;
    
    }
</style>

<div class="boxShadow2">
    <p style="text-align:right">
        Publikuota: @Model.naujienos_sukurimo_data.ToString("yyyy-MM-dd")
        <span style="float:left">
            Autorius: <span style="font-weight:bold">Gytis Šneideraitis</span>
        </span>
    </p>
    <hr />
    <p style="font-size:30px">@Model.pavadinimas</p>
    <hr />
    <p>@Html.Raw(Model.naujienos_tekstas)</p>
</div>
<div style="align-items:center" class="boxShadow2">
    <H4>Nuotraukų galerija</H4>
    <hr />
    @if (Model.nuotraukos.Count != 0)
    {
        <div class="containerPhoto">
            <div class="gallery">
                @foreach (var item in Model.nuotraukos)
                {
                    <a href="~/Nuotraukos/@item.nuotraukos_nuoroda" data-lightbox="models" data-title="@item.nuotraukos_nuoroda">
                        <img class="customImg" src="~/Nuotraukos/@item.nuotraukos_nuoroda" />
                    </a>
                }
            </div>
        </div>
    }
    else
    {
        <p>Nuotraukų nebuvo pridėta</p>
    }
</div>
<div style="margin:2vh">
    <input type="submit" value="< Atgal" onclick="@("window.location.href='" + @Url.Action("Naujienos", "Naujiena") + "'");" class="btn btn-info" />
</div>